# Generated by Django 3.0.8 on 2020-07-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True, verbose_name='number')),
            ],
        ),
    ]
